apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-deployment
spec:
  replicas: 3
  selector: 
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      containers:
        - name: backend-deployment
          image: thetkpark/gdsc-basic-k8s-todo-server:v1
          resources:
            limits:
              memory: "32Mi"
              cpu: "20m"
          ports:
            - containerPort: 5050
          envFrom:
            - configMapRef:
                name: todo-app-configmap
            # - secretRef:
            #     name: todo-app-secret
          env:
          - name: DB_PASSWORD
            value: SuperSecurePassword