apiVersion: apps/v1
kind: Deployment
metadata:
  name: maria-db-depl
spec:
  selector:
    matchLabels:
      app: maria-db
  template:
    metadata:
      labels:
        app: maria-db
    spec:
      containers:
      - name: maria-db
        image: mariadb
        resources:
          limits:
            memory: "128Mi"
            cpu: "50m"
        ports:
        - containerPort: 3306
        env:
          - name: MARIADB_ROOT_PASSWORD
            value: SuperSecurePassword
          - name: MARIADB_DATABASE
            value: todo

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-srv
spec:
  type: ClusterIP
  selector:
    app: maria-db
  ports:
  - port: 3306
    targetPort: 3306
