apiVersion: v1
kind: ConfigMap
metadata:
  name: todo-app-configmap
data:
  DB_HOST: mariadb-clusterip
  DB_PORT: "3306"
  DB_USER: root
  DB_DATABASE: todo

---
apiVersion: v1
kind: Secret
metadata: 
  name: todo-app-secret
type: Opaque
data:
  DB_PASSWORD: U3VwZXJTZWN1cmVQYXNzd29yZAo=

