apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-depl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: todo-backend
  template:
    metadata:
      labels:
        app: todo-backend
    spec:
      restartPolicy: Always
      containers:
      - name: backend-depl
        image: thetkpark/gdsc-basic-k8s-todo-server:v1
        resources:
          limits:
            memory: "32Mi"
            cpu: "20m"
        ports:
        - containerPort: 5050
        env:
          - name: DB_HOST
            value: mariadb-srv
          - name: DB_PORT
            value: "3306"
          - name: DB_USER
            value: root
          - name: DB_PASSWORD
            value: SuperSecurePassword
          - name: DB_DATABASE
            value: todo
